# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - '5431:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=school
    volumes:
      - ./dbSetup.sql:/docker-entrypoint-initdb.d/dbSetup.sql
      - ./fr-en-annuaire-education.csv:/data/fr-en-annuaire-education.csv
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
